In [1]:
from google.colab import drive
import os

if not os.path.exists('/gd'):
    drive.mount('/gd')

In [2]:
import numpy as np

DATA_PATH_FOLDER = "/gd/MyDrive/data_gdpr/"

train_representation = np.load(os.path.join(DATA_PATH_FOLDER, "representation.eng.train.npy"))
train_true_labels = np.load(os.path.join(DATA_PATH_FOLDER, "true_labels.eng.train.npy"))

test_1_representation = np.load(os.path.join(DATA_PATH_FOLDER, "representation.eng.testa.npy"))
test_1_true_labels = np.load(os.path.join(DATA_PATH_FOLDER, "true_labels.eng.testa.npy"))

test_2_representation = np.load(os.path.join(DATA_PATH_FOLDER, "representation.eng.testb.npy"))
test_2_true_labels = np.load(os.path.join(DATA_PATH_FOLDER, "true_labels.eng.testb.npy"))

In [ ]:
from sklearn import linear_model

model = linear_model.LogisticRegressionCV()
model.fit(X=train_representation[:1000], y=train_true_labels[:1000])

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

LogisticRegressionCV()

In [ ]:
print("train acc: ", model.score(X=train_representation, y=train_true_labels))
print("test a acc: ", model.score(X=test_1_representation, y=test_1_true_labels))
print("test b acc: ",model.score(X=test_2_representation, y=test_2_true_labels))

train acc:  0.921082748424553
test a acc:  0.9271659744165127
test b acc:  0.9178749165176552


In [4]:
from sklearn import neighbors

knn_classifier = neighbors.KNeighborsClassifier(n_neighbors=5)
knn_classifier.fit(train_representation, train_true_labels)

KNeighborsClassifier()

In [7]:
# print("train acc: ", knn_classifier.score(X=train_representation, y=train_true_labels))
print("test a acc: ", knn_classifier.score(X=test_1_representation[:1000], y=test_1_true_labels[:1000]))
print("test b acc: ",knn_classifier.score(X=test_2_representation[:1000], y=test_2_true_labels[:1000]))

test a acc:  0.974
test b acc:  0.984


In [14]:
from sklearn import ensemble

forest = ensemble.RandomForestClassifier(n_estimators=1, n_jobs = -1)

forest.fit(train_representation, train_true_labels)

RandomForestClassifier(n_estimators=1, n_jobs=-1)

In [19]:
test_1_pred = forest.predict(test_1_representation)
test_2_pred = forest.predict(test_2_representation)

In [20]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy_1 = accuracy_score(test_1_pred, test_1_true_labels)
print(f'test a acc: : {accuracy_1}')
print(classification_report(test_1_pred, test_1_true_labels))
print(confusion_matrix(test_1_pred, test_1_true_labels))

accuracy_2 = accuracy_score(test_2_pred, test_2_true_labels)
print(f'test b acc: : {accuracy_2}')
print(classification_report(test_2_pred, test_2_true_labels))
print(confusion_matrix(test_2_pred, test_2_true_labels))

test a acc: : 0.8433815148100399


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

       B-LOC       0.00      0.00      0.00        12
      B-MISC       0.00      0.00      0.00        24
       B-ORG       0.00      0.00      0.00        12
       I-LOC       0.46      0.43      0.44     13223
      I-MISC       0.31      0.30      0.31      7715
       I-ORG       0.39      0.32      0.35     15078
       I-PER       0.53      0.54      0.54     18319
           O       0.92      0.93      0.93    253550

    accuracy                           0.84    307933
   macro avg       0.33      0.32      0.32    307933
weighted avg       0.84      0.84      0.84    307933

[[     0      0      0      0      0      0      0     12]
 [     0      0      0      0      6      0      0     18]
 [     0      0      0      0      0      0      0     12]
 [     0      6      0   5736    774   1235   1176   4296]
 [     0     12      0    792   2352    618    624   3317]
 [     0      0      0   1398    762   4842   1872   6

In [21]:
from sklearn import ensemble

forest = ensemble.RandomForestClassifier(n_estimators=10, n_jobs = -1)

forest.fit(train_representation, train_true_labels)

RandomForestClassifier(n_estimators=10, n_jobs=-1)

In [22]:
test_1_pred = forest.predict(test_1_representation)
test_2_pred = forest.predict(test_2_representation)

In [23]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy_1 = accuracy_score(test_1_pred, test_1_true_labels)
print(f'test a acc: : {accuracy_1}')
print(classification_report(test_1_pred, test_1_true_labels))
print(confusion_matrix(test_1_pred, test_1_true_labels))

accuracy_2 = accuracy_score(test_2_pred, test_2_true_labels)
print(f'test b acc: : {accuracy_2}')
print(classification_report(test_2_pred, test_2_true_labels))
print(confusion_matrix(test_2_pred, test_2_true_labels))

test a acc: : 0.9271270049004167
              precision    recall  f1-score   support

      B-MISC       0.25      1.00      0.40         6
       I-LOC       0.62      0.86      0.72      9048
      I-MISC       0.34      0.87      0.49      3006
       I-ORG       0.48      0.78      0.59      7692
       I-PER       0.70      0.92      0.79     14352
           O       1.00      0.93      0.97    273829

    accuracy                           0.93    307933
   macro avg       0.57      0.89      0.66    307933
weighted avg       0.95      0.93      0.94    307933

[[     6      0      0      0      0      0]
 [     6   7812    534    426    216     54]
 [     0    162   2604    108     78     54]
 [     0    588    306   6018    558    222]
 [     0    300    162    612  13134    144]
 [    12   3702   3978   5388   4830 255919]]
test b acc: : 0.9094728224572893


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

       B-LOC       0.00      0.00      0.00         0
      B-MISC       0.00      0.00      0.00         0
       B-ORG       0.00      0.00      0.00         0
       I-LOC       0.59      0.79      0.67     10045
      I-MISC       0.24      0.69      0.35      2170
       I-ORG       0.42      0.73      0.53     10017
       I-PER       0.62      0.88      0.73     13622
           O       0.99      0.92      0.96    289065

    accuracy                           0.91    324919
   macro avg       0.36      0.50      0.41    324919
weighted avg       0.94      0.91      0.92    324919

[[     0      0      0      0      0      0      0      0]
 [     0      0      0      0      0      0      0      0]
 [     0      0      0      0      0      0      0      0]
 [    14      0      0   7910    532   1071    315    203]
 [     0     14      0    175   1498    168    112    203]
 [     0      0      0    840    357   7287    910    

In [3]:
len(train_representation)

1017965

In [7]:
from sklearn.svm import LinearSVC

svm = LinearSVC()

svm.fit(train_representation[:len(train_representation)//10], train_true_labels[:len(train_representation)//10])

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC()

In [8]:
test_1_pred = svm.predict(test_1_representation)
test_2_pred = svm.predict(test_2_representation)

In [9]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy_1 = accuracy_score(test_1_pred, test_1_true_labels)
print(f'test a acc: : {accuracy_1}')
print(classification_report(test_1_pred, test_1_true_labels))
print(confusion_matrix(test_1_pred, test_1_true_labels))

accuracy_2 = accuracy_score(test_2_pred, test_2_true_labels)
print(f'test b acc: : {accuracy_2}')
print(classification_report(test_2_pred, test_2_true_labels))
print(confusion_matrix(test_2_pred, test_2_true_labels))

test a acc: : 0.9769495312291959


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

       B-LOC       0.00      0.00      0.00        12
      B-MISC       0.00      0.00      0.00        36
       I-LOC       0.88      0.90      0.89     12294
      I-MISC       0.73      0.80      0.77      6954
       I-ORG       0.85      0.86      0.86     12378
       I-PER       0.96      0.97      0.97     18697
           O       1.00      0.99      0.99    257562

    accuracy                           0.98    307933
   macro avg       0.63      0.65      0.64    307933
weighted avg       0.98      0.98      0.98    307933

[[     0      0      0      6      0      6      0]
 [     0      0      0     18     12      0      6]
 [     0      0  11112    486    450     84    162]
 [     0     24    426   5568    480     84    372]
 [     0      0    606    468  10692    228    384]
 [     0      0     84    132    187  18144    150]
 [     0      0    336    906    731    270 255319]]
test b acc: : 0.9679427795850658


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

       B-LOC       0.00      0.00      0.00        21
      B-MISC       0.00      0.00      0.00        21
       B-ORG       0.00      0.00      0.00         0
       I-LOC       0.85      0.85      0.85     13384
      I-MISC       0.70      0.71      0.71      6293
       I-ORG       0.82      0.82      0.82     17381
       I-PER       0.95      0.96      0.95     19285
           O       0.99      0.99      0.99    268534

    accuracy                           0.97    324919
   macro avg       0.54      0.54      0.54    324919
weighted avg       0.97      0.97      0.97    324919

[[     0      0      0      0      0      7     14      0]
 [     0      0      0      0     14      0      0      7]
 [     0      0      0      0      0      0      0      0]
 [    14      0      0  11403    350   1155    203    259]
 [     0     49      0    434   4466    532     35    777]
 [    28      7     35   1050    567  14315    392    